import type { Community, ProductEdge, ProductNode } from "@/components/graph"
import { addDays, dayLong, momentLabel, rangeLabel, shortDate, weekdayShort } from "@/lib/dates"
import { recentChange } from "@/lib/trend"
import { api, type ApiNetwork } from "./api"

/**
 * The store the signed-in app shows, loaded from the Constella API (the warehouse's serving views)
 * with a top-level await: every page that imports this module waits for it, so they can all read
 * the data synchronously. Only the signed-in pages import it, and they're lazy-loaded, so the
 * landing page never waits. If the API can't be reached, the import fails and the app shows an
 * error (features/app/AppPage).
 *
 * Communities come from the 90-day network for all customers, so a product keeps its community
 * (and colour) across periods and segments. Their labels are generated by the API from their top
 * products. Networks for other periods and segments live in `networks.ts`.
 */

/* ---------- The store and its dates ---------- */

const store = await api.store()
if (!store.last_complete_day) throw new Error(`${store.name} has no data in the warehouse yet.`)

/** The latest complete day in the data; default ranges end here. */
export const LAST_DATA_DAY = store.last_complete_day

export type PeriodId = "30d" | "90d" | "12m"

export interface Period {
  id: PeriodId
  label: string
  /** "Aug 28 – Sep 26" */
  range: string
  start: string
  end: string
}

const period = (id: PeriodId, label: string, days: number): Period => {
  const start = addDays(LAST_DATA_DAY, -(days - 1))
  return { id, label, range: rangeLabel(start, LAST_DATA_DAY), start, end: LAST_DATA_DAY }
}

export const periods: Period[] = [period("30d", "30 days", 30), period("90d", "90 days", 90), period("12m", "12 months", 365)]
export const periodById = (id: PeriodId) => periods.find((p) => p.id === id) ?? periods[1]
const base = periodById("90d")

/** The last 7 complete days and the 7 before, for Home. */
const thisWeek = { start: addDays(LAST_DATA_DAY, -6), end: LAST_DATA_DAY }
const lastWeek = { start: addDays(LAST_DATA_DAY, -13), end: addDays(LAST_DATA_DAY, -7) }

/* ---------- Fetch ---------- */

const WEEKS = 12
/** Pairs need at least this many orders together to be drawn. */
export const MIN_CO_ORDERS = 5

const [catalog, baseApiNetwork, sales90, weekly, segmentRows, fortnight, salesThisWeek, salesLastWeek, pairsThisWeek, pairsLastWeek] = await Promise.all([
  api.products(),
  api.network({ start: base.start, end: base.end, min_co_orders: MIN_CO_ORDERS }),
  api.sales(base),
  api.weekly(WEEKS, LAST_DATA_DAY),
  api.segments(base),
  api.summary({ start: lastWeek.start, end: thisWeek.end }),
  api.sales(thisWeek),
  api.sales(lastWeek),
  // Every pair, however rare, so Home can compare the two weeks.
  api.network({ ...thisWeek, min_co_orders: 1, min_lift: 0 }),
  api.network({ ...lastWeek, min_co_orders: 1, min_lift: 0 }),
])

export const storeInfo = {
  name: store.name,
  timezone: store.timezone,
  currency: store.currency,
  /** When the warehouse last rebuilt, in the store's time: "Sep 28, 06:00". */
  asOf: store.refreshed_at ? momentLabel(store.refreshed_at, store.timezone) : shortDate(LAST_DATA_DAY),
  /** Paid orders in the 90-day base window. */
  orders90: baseApiNetwork.meta.total_orders,
}

/* ---------- Catalog and communities ---------- */

export const communities: Community[] = baseApiNetwork.communities.map((c) => ({ community: c.community, label: c.label }))

export const communityLabel = (c?: number | null) => communities.find((x) => x.community === c)?.label ?? "No community"

export interface Product {
  /** The SKU. */
  id: string
  label: string
  /** Top-level category. */
  category: string
  community: number | null
  price: number
  /** Orders containing it in an average week (last 90 days). */
  weekly: number
}

const communityOf = new Map(baseApiNetwork.nodes.map((n) => [n.id, n.community]))
const orders90 = new Map(sales90.products.map((p) => [p.id, p.orders]))
const weeklyById = new Map(weekly.products.map((p) => [p.id, p]))
const WEEKS_IN_BASE = 90 / 7

/** Active products, and inactive ones that still sold in the last 12 weeks. */
export const products: Product[] = catalog
  .filter((p) => p.status === "active" || weeklyById.has(p.id))
  .map((p) => ({
    id: p.id,
    label: p.name,
    category: p.top_category,
    community: communityOf.get(p.id) ?? null,
    price: p.price,
    weekly: (orders90.get(p.id) ?? 0) / WEEKS_IN_BASE,
  }))

export const productById = Object.fromEntries(products.map((p) => [p.id, p])) as Record<string, Product>
export const categories = [...new Set(products.map((p) => p.category))].sort()

/** Paid orders in an average week of the base window. */
export const weeklyOrders = storeInfo.orders90 / WEEKS_IN_BASE

/* ---------- Customer segments ---------- */

export type SegmentId = "all" | "champions" | "loyal" | "potential" | "new" | "at_risk" | "hibernating"

export interface Segment {
  id: SegmentId
  label: string
  /** What the RFM scores mean for this group, in plain words. */
  description: string
  /** Share of orders over the last 90 days. */
  share: number
}

export const segments: Segment[] = [
  { id: "all", label: "All customers", description: "Every order in the period", share: 1 },
  ...segmentRows.map((s) => ({ id: s.id as SegmentId, label: s.label, description: s.description, share: s.share })),
]

export const segmentById = (id: SegmentId) => segments.find((s) => s.id === id) ?? segments[0]

/* ---------- Networks ---------- */

export interface NetNode extends ProductNode {
  category: string
  orders: number
  revenue: number
  degree: number
}

export interface NetEdge extends ProductEdge {
  coOrders: number
  /** Share of the source's orders that also have the target, and the other way round. */
  confidenceAB: number
  confidenceBA: number
}

export interface Network {
  nodes: NetNode[]
  edges: NetEdge[]
  orders: number
  /** Products with no pair above the threshold, left out of the drawing. */
  hidden: number
}

/** Adapts an API network; every node gets its store community, so colours stay put. */
export function toNetwork(n: ApiNetwork): Network {
  const nodes = n.nodes
    .filter((x) => productById[x.id])
    .map((x) => ({
      id: x.id,
      label: x.label,
      category: x.category,
      community: productById[x.id].community,
      orders: x.orders,
      revenue: x.revenue,
      degree: x.degree,
      strength: x.strength,
    }))
  const known = new Set(nodes.map((x) => x.id))
  return {
    nodes,
    edges: n.edges
      .filter((e) => known.has(e.source) && known.has(e.target))
      .map((e) => ({
        source: e.source,
        target: e.target,
        coOrders: e.co_orders,
        lift: e.lift,
        confidenceAB: e.conf_source_to_target,
        confidenceBA: e.conf_target_to_source,
      })),
    orders: n.meta.total_orders,
    hidden: products.length - nodes.length,
  }
}

const baseNet = toNetwork(baseApiNetwork)

/** Every pair in the base window (90 days, all customers), for pages that aren't filtered. */
export const baseNetwork = () => baseNet

/* ---------- Weekly sales, 12 weeks ending on the last complete day ---------- */

export const weeks = weekly.week_starts.map((start, i) => ({ id: `w${i}`, label: shortDate(start), long: `Week of ${shortDate(start)}` }))

export interface WeeklySeries {
  revenue: number[]
  units: number[]
}

const zeros = () => weeks.map(() => 0)

export const series: Record<string, WeeklySeries> = Object.fromEntries(
  products.map((p) => {
    const w = weeklyById.get(p.id)
    return [p.id, { revenue: w?.revenue ?? zeros(), units: w?.qty ?? zeros() }]
  }),
)

const sum = (xs: number[]) => xs.reduce((a, b) => a + b, 0)

export { recentChange }

/** Weekly revenue summed over some products. */
export function seriesOf(ids: string[]): number[] {
  return weeks.map((_, i) => sum(ids.map((id) => series[id]?.revenue[i] ?? 0)))
}

export function communitySeries(community: number): number[] {
  return seriesOf(products.filter((p) => p.community === community).map((p) => p.id))
}

export const totals = {
  revenue12w: sum(products.map((p) => sum(series[p.id].revenue))),
}

/** The best seller over the 12 weeks: what pages open on when nothing is chosen. */
export const featuredProduct = [...products].sort((a, b) => sum(series[b.id].revenue) - sum(series[a.id].revenue))[0]?.id ?? ""

/* ---------- The last two weeks, for Home ---------- */

const byDay = new Map(fortnight.daily.map((d) => [d.day, d]))
const weekDays = (start: string) => Array.from({ length: 7 }, (_, i) => addDays(start, i))
const salesMap = (rows: typeof salesThisWeek.products) => new Map(rows.map((p) => [p.id, { orders: p.orders, revenue: p.revenue }]))
const pairMap = (n: ApiNetwork) => new Map(n.edges.map((e) => [`${e.source}|${e.target}`, e.co_orders]))

export const week = {
  current: { ...thisWeek, range: rangeLabel(thisWeek.start, thisWeek.end) },
  previous: { ...lastWeek, range: rangeLabel(lastWeek.start, lastWeek.end) },
  days: weekDays(thisWeek.start).map((id) => ({ id, short: weekdayShort(id), long: dayLong(id) })),
  /** The same weekday one week earlier. */
  previousDays: weekDays(lastWeek.start).map(weekdayShort),
  revenue: {
    current: weekDays(thisWeek.start).map((d) => byDay.get(d)?.revenue ?? 0),
    previous: weekDays(lastWeek.start).map((d) => byDay.get(d)?.revenue ?? 0),
  },
  orders: {
    current: weekDays(thisWeek.start).map((d) => byDay.get(d)?.orders ?? 0),
    previous: weekDays(lastWeek.start).map((d) => byDay.get(d)?.orders ?? 0),
  },
  /** Orders and revenue per product. */
  sales: { current: salesMap(salesThisWeek.products), previous: salesMap(salesLastWeek.products) },
  /** Orders with both products, keyed "skuA|skuB" (sku_a < sku_b). */
  pairs: { current: pairMap(pairsThisWeek), previous: pairMap(pairsLastWeek) },
}
